openapi: 3.0.0
info:
  title: Tenants
  version: '1.0'
  description: ''
servers:
  - url: 'https://api.counterbalance.io'
    description: Production API
paths:
  /v1/tenant:
    get:
      summary: Get Tenant Account
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Tenant-Account'
              examples:
                Response:
                  value:
                    id: d6797ebf-5b00-4a59-b3e5-19711b4c55bb
                    name: Figgis Agency
                    flags:
                      active: true
                      has_subscription: true
                      has_billing_account: true
                      locked: false
                      confirmed: true
                      deleted: false
                    billing_id: cus_GZBdOM86hQZldD
                    locale: en-us
                    primary_contact:
                      id: 1b17e73b-4cf7-4b47-a0f8-46f878ef7bf1
                      name:
                        given: Cyril
                        family: Figgis
                        full: Cyril Figgis
                      email: cyril@figgisagency.com
                      phone:
                        primary:
                          type: null
                          number: null
                    subscription:
                      tier: 3
                      sku: plan_GvzroFXIrnFYdH
                      active: true
                    trial:
                      status: Never Started
                      used: false
                      active: false
                      expired: false
                      expires: 0
                    addresses:
                      mailing: f3643601-d122-47c5-893c-1f108c07d840
                      billing: null
                    milestones:
                      account_created:
                        status: true
                        timestamp: 1517451002
                      account_deleted:
                        status: false
                        timestamp: 0
                      account_confirmation:
                        status: true
                        timestamp: 1580183430
                      onboarded:
                        status: true
                        timestamp: 1580183430
                      accepted_terms:
                        status: false
                        timestamp: 0
                      accepted_billing_terms:
                        status: false
                        timestamp: 0
                      accepted_subscription_terms:
                        status: false
                        timestamp: 0
      operationId: get-v1-tenant
      description: Retrieve the tenant account of the authenticated user
      security:
        - Bearer Token: []
    post:
      summary: Create Tenant Account
      operationId: post-v1-tenant
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
              examples:
                Response:
                  value:
                    success_message: The new tenant account was created! Email confirmation required.
      description: |-
        Signup for and create a new tenant account

        > Once an account is created, it must be confirmed before it can be used
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                given_name:
                  type: string
                family_name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                company_name:
                  type: string
                accept_terms:
                  type: boolean
              required:
                - given_name
                - family_name
                - email
                - password
                - company_name
                - accept_terms
            examples:
              Example:
                value:
                  given_name: Taylor
                  family_name: Vick
                  email: hello@counterbalanceio
                  password: Se@ttle1!
                  company_name: Counterbalance Software
                  accept_terms: true
    patch:
      summary: Update Tenant Account
      operationId: patch-v1-tenant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Tenant-Account'
              examples:
                Response:
                  value:
                    id: d6797ebf-5b00-4a59-b3e5-19711b4c55bb
                    name: Figgis Agency
                    flags:
                      active: true
                      has_subscription: true
                      has_billing_account: true
                      locked: false
                      confirmed: true
                      deleted: false
                    billing_id: cus_GZBdOM86hQZldD
                    locale: en-us
                    primary_contact:
                      id: 1b17e73b-4cf7-4b47-a0f8-46f878ef7bf1
                      name:
                        given: Cyril
                        family: Figgis
                        full: Cyril Figgis
                      email: cyril@figgisagency.com
                      phone:
                        primary:
                          type: null
                          number: null
                    subscription:
                      tier: 3
                      sku: plan_GvzroFXIrnFYdH
                      active: true
                    trial:
                      status: Never Started
                      used: false
                      active: false
                      expired: false
                      expires: 0
                    addresses:
                      mailing: f3643601-d122-47c5-893c-1f108c07d840
                      billing: null
                    milestones:
                      account_created:
                        status: true
                        timestamp: 1517451002
                      account_deleted:
                        status: false
                        timestamp: 0
                      account_confirmation:
                        status: true
                        timestamp: 1580183430
                      onboarded:
                        status: true
                        timestamp: 1580183430
                      accepted_terms:
                        status: false
                        timestamp: 0
                      accepted_billing_terms:
                        status: false
                        timestamp: 0
                      accepted_subscription_terms:
                        status: false
                        timestamp: 0
      description: Update the tenant account of the authenticated user
      security:
        - Bearer Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  maxLength: 240
                  description: Your tenant company name
                primary_contact:
                  type: string
                  format: uuid
                  description: The UUID of the user designated as the primary contact for your account
            examples:
              Example:
                value:
                  name: Figgis Agency
                  primary_contact: 5152763b-7d76-4d22-8484-ff27da40fe98
        description: ''
  /v1/tenant/quota:
    get:
      summary: Get Tenant Quota Summary
      tags: []
      responses: {}
      operationId: get-v1-tenant-quota
  /v1/tenant/confirm:
    post:
      summary: Confirm Tenant Account
      operationId: post-v1-tenant-confirm
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
              examples:
                Example:
                  value:
                    success_message: Tenant account has been successfully confirmed!
      description: |-
        Confirm a newly-created tenant account

        > A confirm operation can only be completed by the user who created the tenant acccount
      security:
        - Bearer Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: number
                  minimum: 6
                  maximum: 6
                  description: A six-digit confirmation code
              required:
                - code
            examples:
              Example:
                value:
                  code: 123456
  /v1/tenant/onboarding:
    parameters: []
    post:
      summary: Complete Tenant Onboarding
      operationId: post-v1-tenant-onboarding
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success_message:
                    type: string
              examples:
                Response:
                  value:
                    success_message: Onboarding has been completed!
      description: Marks the tenant account as having been onboarded
      security:
        - Bearer Token: []
      requestBody:
        content:
          application/json:
            schema:
              type: 'null'
            examples:
              Example:
                value: {}
        description: '*No request body is necesssary for this request*'
  /v1/tenant/preferences:
    get:
      summary: Get Tenant Preferences
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Tenant-Preferences'
      operationId: get-v1-tenant-preferences
      description: Retreieve the platform preferences for the authenticated user's tenant account
      security:
        - Bearer Token: []
components:
  schemas:
    Tenant-Account:
      description: The tenant account object
      type: object
      properties:
        id:
          type: string
          minLength: 1
        name:
          type: string
          minLength: 1
        flags:
          type: object
          properties:
            active:
              type: boolean
            has_subscription:
              type: boolean
            has_billing_account:
              type: boolean
            locked:
              type: boolean
            confirmed:
              type: boolean
            deleted:
              type: boolean
        billing_id:
          type:
            - string
            - 'null'
          minLength: 1
        locale:
          type: string
          minLength: 1
        primary_contact:
          type: object
          properties:
            id:
              type: string
              minLength: 1
            name:
              type: object
              properties:
                given:
                  type: string
                  minLength: 1
                family:
                  type: string
                  minLength: 1
                full:
                  type: string
                  minLength: 1
            email:
              type: string
              minLength: 1
            phone:
              type: object
              properties:
                primary:
                  type: object
                  properties:
                    type: {}
                    number: {}
        subscription:
          type: object
          required:
            - active
          properties:
            tier:
              type: number
            sku:
              type: string
              minLength: 1
            active:
              type: boolean
        trial:
          type: object
          required:
            - status
            - used
            - active
            - expired
            - expires
          properties:
            status:
              type: string
              minLength: 1
            used:
              type: boolean
            active:
              type: boolean
            expired:
              type: boolean
            expires:
              type: number
        addresses:
          type: object
          required:
            - mailing
          properties:
            mailing:
              type: string
              minLength: 1
            billing: {}
        milestones:
          type: object
          required:
            - account_created
            - account_deleted
            - account_confirmation
            - onboarded
            - accepted_terms
            - accepted_billing_terms
            - accepted_subscription_terms
          properties:
            account_created:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
            account_deleted:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
            account_confirmation:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
            onboarded:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
            accepted_terms:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
            accepted_billing_terms:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
            accepted_subscription_terms:
              type: object
              required:
                - status
                - timestamp
              properties:
                status:
                  type: boolean
                timestamp:
                  type: number
      required:
        - trial
        - addresses
        - milestones
      title: Tenant Account
      x-examples:
        Example:
          id: d6797ebf-5b00-4a59-b3e5-19711b4c55bb
          name: Figgis Agency
          flags:
            active: true
            has_subscription: true
            has_billing_account: true
            locked: false
            confirmed: true
            deleted: false
          billing_id: cus_GZBdOM86hQZldD
          locale: en-us
          primary_contact:
            id: 1b17e73b-4cf7-4b47-a0f8-46f878ef7bf1
            name:
              given: Cyril
              family: Figgis
              full: Cyril Figgis
            email: cyril@figgisagency.com
            phone:
              primary:
                type: null
                number: null
          subscription:
            tier: 3
            sku: plan_GvzroFXIrnFYdH
            active: true
          trial:
            status: Never Started
            used: false
            active: false
            expired: false
            expires: 0
          addresses:
            mailing: f3643601-d122-47c5-893c-1f108c07d840
            billing: null
          milestones:
            account_created:
              status: true
              timestamp: 1517451002
            account_deleted:
              status: false
              timestamp: 0
            account_confirmation:
              status: true
              timestamp: 1580183430
            onboarded:
              status: true
              timestamp: 1580183430
            accepted_terms:
              status: false
              timestamp: 0
            accepted_billing_terms:
              status: false
              timestamp: 0
            accepted_subscription_terms:
              status: false
              timestamp: 0
    Tenant-Quota-Summary:
      description: ''
      type: object
      title: Tenant Quota Summary
      properties:
        tenant:
          type: object
          required:
            - id
            - subscription_sku
            - billing_id
          properties:
            id:
              type: string
              minLength: 1
            subscription_sku:
              type:
                - string
                - 'null'
              minLength: 1
            billing_id:
              type:
                - string
                - 'null'
              minLength: 1
        quotas:
          type: object
          required:
            - seat
            - user
            - record_user
            - department
            - site
            - domain
            - managed_device
          properties:
            seat:
              type: object
              required:
                - usage
                - quota
                - remaining
                - status
              properties:
                usage:
                  type: number
                quota:
                  type:
                    - object
                    - 'null'
                  properties:
                    included:
                      type: number
                    purchased:
                      type: number
                    total:
                      type: number
                remaining:
                  type: number
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
            user:
              type: object
              required:
                - usage
                - quota
                - remaining
                - status
              properties:
                usage:
                  type: number
                quota:
                  type:
                    - object
                    - 'null'
                  required:
                    - included
                    - purchased
                    - total
                  properties:
                    included:
                      type: number
                    purchased:
                      type: number
                    total:
                      type: number
                remaining:
                  type: number
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
            record_user:
              type: object
              required:
                - usage
                - status
              properties:
                usage:
                  type: number
                quota: {}
                remaining: {}
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
            department:
              type: object
              required:
                - usage
                - quota
                - remaining
                - status
              properties:
                usage:
                  type: number
                quota:
                  type:
                    - object
                    - 'null'
                  required:
                    - included
                    - purchased
                    - total
                  properties:
                    included:
                      type: number
                    purchased:
                      type: number
                    total:
                      type: number
                remaining:
                  type: number
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
            site:
              type: object
              required:
                - usage
                - quota
                - remaining
                - status
              properties:
                usage:
                  type: number
                quota:
                  type:
                    - object
                    - 'null'
                  required:
                    - included
                    - purchased
                    - total
                  properties:
                    included:
                      type: number
                    purchased:
                      type: number
                    total:
                      type: number
                remaining:
                  type: number
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
            domain:
              type: object
              required:
                - usage
                - status
              properties:
                usage:
                  type: number
                quota: {}
                remaining: {}
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
            managed_device:
              type: object
              required:
                - usage
                - quota
                - remaining
                - status
              properties:
                usage:
                  type: number
                quota:
                  type:
                    - object
                    - 'null'
                  required:
                    - included
                    - purchased
                    - total
                  properties:
                    included:
                      type: number
                    purchased:
                      type: number
                    total:
                      type: number
                remaining:
                  type: number
                status:
                  type: object
                  required:
                    - can_add_more
                    - is_exceeded
                  properties:
                    can_add_more:
                      type: boolean
                    is_exceeded:
                      type: boolean
        subscription:
          type: object
          required:
            - base
            - purchased_items
          properties:
            base:
              type: object
              required:
                - id
                - name
                - tier
                - enabled
                - billing_frequency
                - seat_price
                - included_quotas
                - included_features
              properties:
                id:
                  type: string
                  minLength: 1
                name:
                  type: string
                  minLength: 1
                tier:
                  type: number
                enabled:
                  type: boolean
                billing_frequency:
                  type: string
                  minLength: 1
                seat_price:
                  type: number
                included_quotas:
                  type: object
                  required:
                    - seat
                    - user
                    - department
                    - site
                    - building
                    - managed_device
                    - device_templates
                  properties:
                    seat:
                      type: number
                    user:
                      type: number
                    record_user: {}
                    department:
                      type: number
                    domain: {}
                    site:
                      type: number
                    building:
                      type: number
                    managed_device:
                      type: number
                    device_templates:
                      type: number
                included_features:
                  type: array
                  items:
                    type: object
            purchased_items:
              type: array
              uniqueItems: true
              minItems: 1
              items:
                type: object
                properties:
                  id:
                    type: string
                    minLength: 1
                  product:
                    type: string
                    minLength: 1
                  plan:
                    type: string
                    minLength: 1
                  quantity:
                    type: number
                required:
                  - id
                  - product
                  - plan
                  - quantity
        features:
          type: array
          items:
            type: object
      required:
        - tenant
        - quotas
        - subscription
        - features
    Tenant-Preferences:
      description: ''
      type: object
      properties:
        display_name_format:
          type: string
          minLength: 1
        shell:
          type: object
          properties:
            theme:
              type: string
              minLength: 1
            pagination:
              type: object
              properties:
                enabled:
                  type: boolean
                default_limit:
                  type: number
                  default: 10
            disabled_applications:
              type: array
              items:
                type: string
      title: Tenant Account Preferences
  securitySchemes:
    Bearer Token:
      type: http
      scheme: bearer
